"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { trackEvent } from "@/lib/analytics/track";
import { deduplicateResults } from "@/lib/meta/branded-content/pagination";
import type { BrandedContentPlatform, BrandedContentResult, BrandedContentSearchResponse } from "@/lib/meta/branded-content/types";
import { AccountField } from "./account-field"; import { DateRangeFilter, type DatePreset } from "./date-range-filter"; import { EmptyResults } from "./empty-results"; import { ErrorState } from "./error-state"; import { LoadingResults } from "./loading-results"; import { PlatformSelector } from "./platform-selector"; import { PremiumPreview } from "./premium-preview"; import { ResultsList } from "./results-list"; import { SearchSummary } from "./search-summary";

type Comparison = { metaCount:number; apifyCount:number; common:number; metaExclusive:number; apifyExclusive:number; duplicationRate:number; metaDurationMs:number; apifyDurationMs:number; estimatedApifyCost:number };
type Props = { allowed:boolean; reason?:string; dashboardEnabled:boolean; paginationEnabled:boolean; premiumPreview:boolean; showProviderComparison?:boolean };
function iso(date:Date){return date.toISOString().slice(0,10)} function range(days:number){const end=new Date();const start=new Date();start.setUTCDate(start.getUTCDate()-days);return{min:iso(start),max:iso(end)}}
export function BrandedContentSearch({allowed,reason,dashboardEnabled,paginationEnabled,premiumPreview,showProviderComparison=false}:Props){
  const initial=useMemo(()=>range(30),[]);const[platform,setPlatform]=useState<BrandedContentPlatform>("instagram");const[account,setAccount]=useState("");const[preset,setPreset]=useState<DatePreset>("30");const[dateMin,setDateMin]=useState(initial.min);const[dateMax,setDateMax]=useState(initial.max);const[errors,setErrors]=useState<{account?:string;date?:string}>({});const[results,setResults]=useState<BrandedContentResult[]>([]);const[comparison,setComparison]=useState<Comparison|null>(null);const[pagination,setPagination]=useState<{hasNextPage:boolean;after:string|null}>({hasNextPage:false,after:null});const[state,setState]=useState<"initial"|"loading"|"results"|"empty"|"error">("initial");const[message,setMessage]=useState("");const[loadingMore,setLoadingMore]=useState(false);const controller=useRef<AbortController|null>(null);useEffect(()=>()=>controller.current?.abort(),[]);
  function choosePreset(value:DatePreset){setPreset(value);setErrors((current)=>({...current,date:undefined}));if(value!=="custom"){const next=range(Number(value));setDateMin(next.min);setDateMax(next.max)}} function changePlatform(value:BrandedContentPlatform){setPlatform(value);setAccount("");setErrors((current)=>({...current,account:undefined}))}
  function validate(){const next:typeof errors={};if(platform==="instagram"?!/^@?[a-zA-Z0-9._]{1,30}$/.test(account.trim())||account.includes(".."):!/^https:\/\/(?:www\.)?facebook\.com\/[^/?#]+\/?$/.test(account.trim()))next.account=platform==="instagram"?"Informe um nome de usuário válido do Instagram.":"Informe uma URL válida de Página do Facebook.";const today=iso(new Date());if(!dateMin||!dateMax||dateMin>dateMax||dateMax>today||dateMin<"2023-08-17")next.date="Informe um período válido entre 17/08/2023 e hoje.";setErrors(next);return Object.keys(next).length===0}
  async function execute(after?:string){if(!after&&!validate())return;controller.current?.abort();controller.current=new AbortController();if(after)setLoadingMore(true);else{setState("loading");setResults([]);setComparison(null);trackEvent("branded_content_search_started",{platform,period_selected:preset})}const query=new URLSearchParams({platform,dateMin,dateMax,...(platform==="instagram"?{username:account}:{pageUrl:account}),...(after?{after}:{})});try{const response=await fetch(`/api/branded-content/search?${query}`,{signal:controller.current.signal,headers:{Accept:"application/json"}});const body:unknown=await response.json();if(!response.ok){const error=body&&typeof body==="object"&&"error" in body?(body as{error?:{message?:string}}).error:null;throw new Error(error?.message||"O serviço de pesquisa está temporariamente indisponível.")}const data=body as BrandedContentSearchResponse&{comparison?:Comparison};const merged=deduplicateResults(after?[...results,...data.results]:data.results);setResults(merged);setComparison(data.comparison||null);setPagination(data.pagination);setState(merged.length?"results":"empty");trackEvent(merged.length?"branded_content_search_completed":"branded_content_search_empty",{platform,period_selected:preset,result_count:merged.length,cache_status:data.meta.fromCache?"hit":"miss"})}catch(error){if(error instanceof Error&&error.name==="AbortError")return;setMessage(error instanceof Error?error.message:"Não foi possível concluir a pesquisa.");if(!after)setState("error");trackEvent("branded_content_search_failed",{platform,period_selected:preset,status:"failed"})}finally{setLoadingMore(false)}}
  if(!allowed)return premiumPreview?<PremiumPreview/>:<ErrorState message={reason||"Este recurso está temporariamente indisponível."}/>;
  return <section className="branded-tool" aria-labelledby="branded-tool-title"><div className="branded-tool-heading"><span>PESQUISA DE CONTEÚDO DE MARCA</span><h2 id="branded-tool-title">Encontre parcerias declaradas</h2><p>Informe uma conta e escolha o período. A cobertura pode variar conforme a fonte disponível.</p></div><form onSubmit={(event)=>{event.preventDefault();void execute()}} noValidate><PlatformSelector value={platform} onChange={changePlatform} disabled={state==="loading"}/><AccountField platform={platform} value={account} onChange={(value)=>{setAccount(value);setErrors((current)=>({...current,account:undefined}))}} error={errors.account} disabled={state==="loading"}/><DateRangeFilter preset={preset} dateMin={dateMin} dateMax={dateMax} onPreset={choosePreset} onDateMin={setDateMin} onDateMax={setDateMax} error={errors.date} disabled={state==="loading"}/><button className="button" disabled={state==="loading"} aria-busy={state==="loading"}>{state==="loading"?"Pesquisando…":"Pesquisar conteúdos"}</button></form><div aria-live="polite">{state==="loading"&&<LoadingResults/>}{state==="error"&&<ErrorState message={message}/>} {state==="empty"&&<EmptyResults/>}{state==="results"&&<><p className="branded-found">Encontramos <strong>{results.length}</strong> conteúdos carregados associados a esta conta. Esse número não representa necessariamente o total existente.</p>{showProviderComparison&&comparison&&<section className="branded-summary"><h3>Comparação dos provedores</h3><div className="branded-summary-stats"><article><strong>{comparison.metaCount}</strong><small>Meta</small></article><article><strong>{comparison.apifyCount}</strong><small>Apify</small></article><article><strong>{comparison.common}</strong><small>em comum</small></article><article><strong>{Math.round(comparison.duplicationRate*100)}%</strong><small>sobreposição</small></article></div><p>Exclusivos: Meta {comparison.metaExclusive}; Apify {comparison.apifyExclusive}. Duração: {comparison.metaDurationMs} ms / {comparison.apifyDurationMs} ms. Custo Apify estimado: US$ {comparison.estimatedApifyCost.toFixed(4)}.</p></section>}<ResultsList results={results} platform={platform} onOpen={()=>trackEvent("branded_content_result_opened",{platform})}/><SearchSummary results={results} dashboardEnabled={dashboardEnabled}/>{paginationEnabled&&pagination.hasNextPage&&pagination.after&&<div className="branded-load-more"><button className="button button-ghost" disabled={loadingMore} onClick={()=>{trackEvent("branded_content_load_more",{platform,result_count:results.length});void execute(pagination.after!);}}>{loadingMore?"Carregando…":"Carregar mais resultados"}</button></div>}</>}</div></section>;
}
