import type { PageCatalogEntry, PageKey } from "@/lib/seo/types";

export const pageCatalog = [
  { key: "home", route: "/", label: "Página inicial", group: "Institucional", defaults: { title: "Alcance IA — análise inteligente para Instagram", description: "Analise dados públicos do Instagram com métricas transparentes e recomendações práticas.", alternates: { canonical: "/" } } },
  { key: "about", route: "/quem-somos", label: "Quem somos", group: "Institucional", defaults: { title: "Quem somos", description: "Conheça a visão e os princípios da Alcance IA.", alternates: { canonical: "/quem-somos" } } },
  { key: "how_it_works", route: "/como-funciona", label: "Como funciona", group: "Institucional", defaults: { title: "Como funciona", description: "Conheça o fluxo transparente da experiência Alcance IA.", alternates: { canonical: "/como-funciona" } } },
  { key: "resources", route: "/recursos", label: "Recursos", group: "Institucional", defaults: { title: "Recursos", description: "Conheça os recursos ativos e planejados da Alcance IA.", alternates: { canonical: "/recursos" } } },
  { key: "contact", route: "/contato", label: "Contato", group: "Institucional", defaults: { title: "Contato", description: "Fale com a equipe da Alcance IA.", alternates: { canonical: "/contato" } } },
  { key: "privacy_policy", route: "/politica-de-privacidade", label: "Política de Privacidade", group: "Legal", defaults: { title: "Política de Privacidade", description: "Como a Alcance IA trata dados pessoais e protege a privacidade.", alternates: { canonical: "/politica-de-privacidade" } } },
  { key: "terms", route: "/termos-de-uso", label: "Termos de Uso", group: "Legal", defaults: { title: "Termos de Uso", description: "Condições para uso responsável da Alcance IA.", alternates: { canonical: "/termos-de-uso" } } },
  { key: "cookies_policy", route: "/politica-de-cookies", label: "Política de Cookies", group: "Legal", defaults: { title: "Política de Cookies", description: "Entenda e controle as categorias de cookies da Alcance IA.", alternates: { canonical: "/politica-de-cookies" } } },
  { key: "data_deletion", route: "/exclusao-de-dados", label: "Exclusão de Dados", group: "Legal", defaults: { title: "Exclusão de Dados", description: "Como solicitar a exclusão de dados tratados pela Alcance IA.", alternates: { canonical: "/exclusao-de-dados" } } },
  { key: "hashtags", route: "/recursos/hashtags", label: "Hashtags", group: "Recursos", defaults: { title: "Hashtags", description: "Explore hashtags relacionadas com metodologia transparente.", alternates: { canonical: "/recursos/hashtags" } } },
  { key: "trending_reels", route: "/recursos/reels-em-alta", label: "Reels em alta", group: "Recursos", defaults: { title: "Reels em alta", description: "Consulte tendências de Reels com dados públicos e contexto.", alternates: { canonical: "/recursos/reels-em-alta" } } },
  { key: "category_reels", route: "/recursos/reels-por-categoria", label: "Reels por categoria", group: "Recursos", defaults: { title: "Reels por categoria", description: "Descubra Reels organizados por categorias editoriais.", alternates: { canonical: "/recursos/reels-por-categoria" } } },
  { key: "branded_content", route: "/recursos/conteudo-de-marca", label: "Conteúdo de marca", group: "Recursos", defaults: { title: "Conteúdo de marca", description: "Pesquise conteúdo de marca público com filtros e fontes identificadas.", alternates: { canonical: "/recursos/conteudo-de-marca" } } },
  { key: "whatsapp_link_generator", route: "/recursos/gerador-link-whatsapp", label: "Gerador de Link WhatsApp Curto", group: "Recursos", defaults: { title: "Gerador de Link WhatsApp Curto Grátis | Alcance IA", description: "Crie gratuitamente um link direto para seu WhatsApp com número brasileiro e mensagem personalizada. Copie e compartilhe em sites e redes sociais.", alternates: { canonical: "/recursos/gerador-link-whatsapp" }, keywords: ["gerador de link WhatsApp", "criar link WhatsApp", "link WhatsApp com mensagem", "criar link wa.me"] } },
  { key: "whatsapp_link_manager", route: "/recursos/gerenciador-links-whatsapp", label: "Gerenciador de Links WhatsApp", group: "Recursos", defaults: { title: "Gerenciador de Links WhatsApp com QR Code | Alcance IA", description: "Crie links curtos do WhatsApp, gere QR Codes e acompanhe cliques em um painel simples. Organize e gerencie seus links com a Alcance IA.", alternates: { canonical: "/recursos/gerenciador-links-whatsapp" }, keywords: ["gerenciador de links WhatsApp", "link curto WhatsApp", "QR Code WhatsApp", "acompanhar cliques WhatsApp", "criar link WhatsApp", "link WhatsApp com mensagem"] } },
] as const satisfies readonly PageCatalogEntry[];

export const pageCatalogByKey = Object.fromEntries(pageCatalog.map((page) => [page.key, page])) as Record<PageKey, PageCatalogEntry>;
export const pageKeys = pageCatalog.map((page) => page.key) as [PageKey, ...PageKey[]];

export function getCatalogPage(key: PageKey) { return pageCatalogByKey[key]; }
