import Image from "next/image";
import Link from "next/link";
import { AnalyticsLink } from "@/components/analytics/analytics-link";
import { formatCompactNumber } from "@/lib/analysis/analysis-formatters";
import type { InstagramPost } from "@/lib/social-providers/contracts/instagram-post";

const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "Data não disponível";

export function AnalysisTopPosts({ posts, requestId }: { posts: InstagramPost[]; requestId: string }) {
  return <section className="analysis-section" id="publicacoes"><div className="analysis-section-heading"><span>06</span><div><h2>Publicações em destaque</h2><p>Conteúdos ordenados pelas interações públicas conhecidas.</p></div></div>{posts.length ? <div className="analysis-post-grid">{posts.map((post, index) => { const type = post.mediaType === "video" ? "Reel" : post.mediaType === "carousel" ? "Carrossel" : "Imagem"; const views = post.playCount ?? post.viewCount; return <article key={post.providerPostId || post.shortcode || index}><div className="analysis-post-media">{post.thumbnailUrl ? <Image src={post.thumbnailUrl} alt={`Miniatura pública do ${type.toLowerCase()} em ${formatDate(post.publishedAt)}`} fill sizes="(max-width: 620px) calc(100vw - 28px), (max-width: 900px) 50vw, 33vw" /> : <span className="analysis-post-placeholder" aria-hidden="true">{post.mediaType === "video" ? "▶" : "□"}</span>}<b>#{index + 1}</b><span className="analysis-post-type">{type}</span></div><div className="analysis-post-copy"><time dateTime={post.publishedAt || undefined}>{formatDate(post.publishedAt)}</time><p>{post.caption?.slice(0, 135) || "Sem legenda disponível."}</p><dl><div><dt>Curtidas</dt><dd>{formatCompactNumber(post.likeCount)}</dd></div><div><dt>Comentários</dt><dd>{formatCompactNumber(post.commentCount)}</dd></div>{views !== null && <div><dt>Views</dt><dd>{formatCompactNumber(views)}</dd></div>}</dl>{post.permalink && <AnalyticsLink href={post.permalink} eventName="analysis_post_clicked" properties={{ request_id: requestId, cta_location: "top_posts" }}>Ver publicação <span aria-hidden="true">↗</span></AnalyticsLink>}</div></article>; })}</div> : <div className="analysis-empty-state"><span aria-hidden="true">□</span><div><h3>Ainda não há publicações suficientes</h3><p>Quando novos conteúdos públicos estiverem disponíveis, esta seção poderá comparar os destaques.</p><Link href="/#analisar">Tentar novamente no futuro</Link></div></div>}</section>;
}
