import { AnalyticsLink } from "@/components/analytics/analytics-link";
import { AnalysisSectionTracker } from "@/components/analysis/analysis-section-tracker";
import { formatCompactNumber, formatDecimal, formatPercentage } from "@/lib/analysis/analysis-formatters";
import type { ProfileProductInsights, RankedReel } from "@/lib/product-features/profile-insights";

function ReelRanking({ title, description, items, metric, requestId }: { title: string; description: string; items: RankedReel[]; metric: "views" | "engagement" | "relative" | "interactions"; requestId: string }) {
  return <article className="analysis-reel-ranking"><header><span>{title}</span><p>{description}</p></header>{items.length ? <ol>{items.map((item, index) => <li key={item.post.providerPostId || item.post.shortcode || index}><b>{index + 1}</b><div><strong>{item.post.caption?.trim().slice(0, 72) || "Reel sem legenda"}</strong><small>{metric === "views" ? `${formatCompactNumber(item.views)} visualizações` : metric === "engagement" ? `${formatPercentage(item.engagementRate)} por visualização` : metric === "interactions" ? `${formatCompactNumber(item.interactions)} interações` : `${formatPercentage(item.relativePerformance)} dos seguidores atuais`}</small></div>{item.post.permalink && <AnalyticsLink href={item.post.permalink} eventName="analysis_top_post_clicked" properties={{ request_id: requestId, cta_location: `reels_${metric}` }} aria-label={`Abrir Reel número ${index + 1}`}>↗</AnalyticsLink>}</li>)}</ol> : <p className="analysis-ranking-empty">O campo necessário não estava disponível em Reels suficientes.</p>}</article>;
}

export function AnalysisProductInsights({ insights, requestId }: { insights: ProfileProductInsights; requestId: string }) {
  const hashtagAllowed = insights.access.profile_hashtag_analysis?.allowed;
  const topHashtagsAllowed = insights.access.profile_top_hashtags?.allowed;
  const reelsAllowed = insights.access.profile_top_reels?.allowed;
  const audioAllowed = insights.access.profile_audio_analysis?.allowed;
  if (!hashtagAllowed && !reelsAllowed && !audioAllowed) return null;
  return <>
    {hashtagAllowed && <section className="analysis-section" id="hashtags"><AnalysisSectionTracker requestId={requestId} sectionId="profile_hashtags" /><div className="analysis-section-heading"><span>10</span><div><h2>Hashtags utilizadas</h2><p>Frequência observada apenas nas legendas já coletadas; nenhuma busca externa foi realizada.</p></div></div><div className="analysis-hashtag-summary"><article><span>USO NA AMOSTRA</span><strong>{formatDecimal(insights.hashtags.averagePerPost, 1)}</strong><small>média · mediana {formatDecimal(insights.hashtags.medianPerPost, 1)} · {insights.hashtags.totalUses} usos · {insights.hashtags.unique} únicas · {insights.hashtags.repeated} repetidas · {insights.hashtags.postsWithoutHashtags} posts sem hashtags · top 5 concentra {formatPercentage(insights.hashtags.topFiveConcentration)}</small></article>{topHashtagsAllowed && <article><span>MAIS USADAS</span>{insights.hashtags.top.length ? <ul>{insights.hashtags.top.map((item) => <li key={item.hashtag}><b>#{item.hashtag}</b><span>{item.count} {item.count === 1 ? "post" : "posts"}</span></li>)}</ul> : <p>Nenhuma hashtag foi observada na amostra.</p>}</article>}</div>{topHashtagsAllowed && insights.hashtags.performance.length > 0 && <div className="analysis-hashtag-performance"><h3>Hashtags em destaque na amostra</h3><p>Associação descritiva, sem afirmar que a hashtag causou o desempenho.</p><div>{insights.hashtags.performance.map((item) => <article key={item.hashtag}><strong>#{item.hashtag}</strong><small>{item.posts} posts</small><dl><div><dt>Interações medianas</dt><dd>{formatCompactNumber(item.medianInteractions)}</dd></div><div><dt>Views medianas</dt><dd>{formatCompactNumber(item.medianViews)}</dd></div><div><dt>Desempenho proporcional</dt><dd>{formatPercentage(item.medianRelativePerformance)}</dd></div></dl></article>)}</div></div>}</section>}
    {reelsAllowed && insights.reels.total > 0 && <section className="analysis-section" id="reels-em-destaque"><AnalysisSectionTracker requestId={requestId} sectionId="profile_reel_rankings" /><div className="analysis-section-heading"><span>11</span><div><h2>Reels em destaque</h2><p>Quatro critérios independentes sobre a amostra pública. Um Reel pode aparecer em mais de uma lista.</p></div></div><div className="analysis-reel-rankings">{insights.access.profile_reels_by_views?.allowed && <ReelRanking title="Mais visualizados" description="Plays ou visualizações públicas." items={insights.reels.byViews} metric="views" requestId={requestId} />}{insights.access.profile_reels_by_engagement?.allowed && <ReelRanking title="Maior engajamento" description="(Curtidas + comentários) ÷ visualizações." items={insights.reels.byEngagement} metric="engagement" requestId={requestId} />}{insights.access.profile_reels_relative_performance?.allowed && <ReelRanking title="Desempenho proporcional" description="Visualizações ÷ seguidores atuais." items={insights.reels.byRelativePerformance} metric="relative" requestId={requestId} />}<ReelRanking title="Mais interações" description="Curtidas + comentários públicos." items={insights.reels.byInteractions} metric="interactions" requestId={requestId} /></div><p className="analysis-method-note">Campos ausentes são excluídos de cada ranking, nunca convertidos em zero. Excluídos: {insights.reels.excluded.missingViews} sem views; {insights.reels.excluded.missingInteractions} sem interações completas; {insights.reels.excluded.missingFollowers} sem denominador de seguidores.</p></section>}
    {audioAllowed && <section className="analysis-section" id="audios"><div className="analysis-section-heading"><span>12</span><div><h2>Áudios utilizados</h2><p>Resumo dos áudios que já vieram nos Reels normalizados; nenhuma chamada adicional foi feita.</p></div></div><div className="analysis-audio-summary">{insights.audio.top.length ? insights.audio.top.map((item) => <span key={item.label}><b>{item.label}</b><small>{item.count} {item.count === 1 ? "Reel" : "Reels"} · média de {formatCompactNumber(item.averageViews)} views · {formatCompactNumber(item.averageInteractions)} interações</small></span>) : <p>O campo de áudio estava indisponível nesta amostra.</p>}</div></section>}
  </>;
}
