import { formatCompactNumber, formatDecimal, formatPercentage } from "@/lib/analysis/analysis-formatters";
import type { RecentTrendResult } from "@/lib/analysis/metrics";
import { AnalysisSectionTracker } from "./analysis-section-tracker";

const metricLabels = { likes: "Curtidas medianas", comments: "Comentários medianos", engagement: "Engajamento mediano", reel_views: "Views medianas de Reels", frequency: "Publicações por semana" };
const classificationLabels = { improving: "Melhora aparente", stable: "Estabilidade", apparent_decline: "Queda aparente", insufficient: "Dados insuficientes" };
const value = (metric: keyof typeof metricLabels, number: number | null) => metric === "engagement" ? formatPercentage(number) : metric === "frequency" ? formatDecimal(number, 1) : formatCompactNumber(number);
export function AnalysisRecentTrend({ trend, requestId }: { trend: RecentTrendResult; requestId: string }) {
  return <section className="analysis-section" id="tendencia"><AnalysisSectionTracker requestId={requestId} sectionId="recent_trend" /><div className="analysis-section-heading"><span>05</span><div><h2>Tendência recente</h2><p>Comparação entre grupos cronológicos equivalentes; não representa crescimento do perfil.</p></div></div><div className="analysis-trend-card"><header><div><span>LEITURA DO PERÍODO</span><h3>{classificationLabels[trend.classification]}</h3></div><small>{trend.olderGroupSize} posts anteriores × {trend.recentGroupSize} recentes</small></header>{trend.available ? <div className="analysis-trend-grid">{trend.comparisons.filter((item) => item.older !== null && item.recent !== null).map((item) => <article key={item.metric}><span>{metricLabels[item.metric]}</span><div><small>Anterior</small><strong>{value(item.metric, item.older)}</strong></div><div><small>Recente</small><strong>{value(item.metric, item.recent)}</strong></div><b>{item.changePercent === null ? "—" : `${item.changePercent > 0 ? "+" : ""}${formatDecimal(item.changePercent, 1)}%`}</b></article>)}</div> : <p className="analysis-advanced-empty">São necessárias mais publicações com datas e métricas comparáveis para identificar uma tendência.</p>}</div></section>;
}
