import { formatDecimal } from "@/lib/analysis/analysis-formatters";
import { profileCriterionLabels } from "@/lib/analysis/metrics/profile-completeness";
import type { AdvancedAnalysisMetrics } from "@/lib/analysis/metrics";
import { AnalysisSectionTracker } from "./analysis-section-tracker";

const classifications = { incomplete: "Incompleto", basic: "Básico", well_filled: "Bem preenchido", complete: "Completo", unavailable: "Indisponível" };
export function AnalysisProfileCompleteness({ metrics, requestId }: { metrics: AdvancedAnalysisMetrics; requestId: string }) {
  const completeness = metrics.profileCompleteness; if (!completeness) return null; const ratio = metrics.followerFollowingRatio;
  return <section className="analysis-section" id="completude"><AnalysisSectionTracker requestId={requestId} sectionId="profile_completeness" /><div className="analysis-section-heading"><span>02</span><div><span className="analysis-heading-kicker">ESTRUTURA DO PERFIL</span><h2>Completude do perfil</h2><p>Presença dos elementos públicos básicos — sem julgar a qualidade estratégica do conteúdo.</p></div></div><div className="analysis-completeness-grid"><article className="analysis-completeness-score"><div><strong>{completeness.score ?? "—"}<small>%</small></strong><span>{classifications[completeness.classification]}</span></div><i aria-label={`${completeness.score ?? 0}% dos critérios preenchidos`}><em style={{ width: `${completeness.score ?? 0}%` }} /></i><p>A pontuação representa apenas preenchimento de campos públicos.</p></article><article className="analysis-criteria-card"><div><h3>Itens presentes</h3><ul>{completeness.completedCriteria.map((item) => <li key={item}><span aria-hidden="true">✓</span>{profileCriterionLabels[item]}</li>)}</ul></div><div><h3>O que pode ser completado</h3>{completeness.missingCriteria.length ? <ul>{completeness.missingCriteria.map((item) => <li key={item}><span aria-hidden="true">○</span>{profileCriterionLabels[item]}</li>)}</ul> : <p>Todos os critérios disponíveis estão preenchidos.</p>}</div></article></div>{ratio && <aside className="analysis-ratio-note"><strong>Relação seguidores/seguindo: {ratio.available ? formatDecimal(ratio.ratio, 1) : "Não disponível"}</strong><p>{ratio.description}</p></aside>}</section>;
}
