import { formatDecimal, formatPercentage } from "@/lib/analysis/analysis-formatters";
import type { AdvancedAnalysisMetrics } from "@/lib/analysis/metrics";
import { AnalysisSectionTracker } from "./analysis-section-tracker";

const stabilityLabels = { stable: "Estável", moderately_variable: "Moderadamente variável", highly_variable: "Muito variável", insufficient: "Dados insuficientes" };
const concentrationLabels = { distributed: "Desempenho distribuído", partially_concentrated: "Parcialmente concentrado", highly_concentrated: "Altamente concentrado", insufficient: "Dados insuficientes" };
export function AnalysisEngagementDiagnostics({ metrics, requestId }: { metrics: AdvancedAnalysisMetrics; requestId: string }) {
  const stability = metrics.engagementStability, concentration = metrics.performanceConcentration; if (!stability && !concentration) return null;
  return <section className="analysis-section" id="estabilidade"><AnalysisSectionTracker requestId={requestId} sectionId="engagement_stability" /><div className="analysis-section-heading"><span>04</span><div><h2>Estabilidade e concentração</h2><p>Como as interações se distribuem entre as publicações analisadas.</p></div></div><div className="analysis-diagnostic-grid">{stability && <article><span>ESTABILIDADE</span><h3>{stabilityLabels[stability.classification]}</h3><p>{stability.explanation}</p><dl><div><dt>Média ÷ mediana</dt><dd>{formatDecimal(stability.meanMedianRatio, 2)}</dd></div><div><dt>Conteúdos fora da curva</dt><dd>{stability.available ? stability.outliersCount : "—"}</dd></div></dl><small>Confiança {stability.confidence.level === "high" ? "alta" : stability.confidence.level === "medium" ? "média" : "baixa"} · {stability.confidence.sampleSize} posts</small></article>}{concentration && <article><span>CONCENTRAÇÃO</span><h3>{concentrationLabels[concentration.classification]}</h3><p>{concentration.available ? `Os três melhores conteúdos concentraram ${formatPercentage(concentration.topThreePercent)} das interações observadas.` : "Ainda não há conteúdos suficientes para avaliar concentração."}</p><dl><div><dt>Melhor post</dt><dd>{formatPercentage(concentration.topPostPercent)}</dd></div><div><dt>Top 20%</dt><dd>{formatPercentage(concentration.topTwentyPercent)}</dd></div></dl><small>Visualizações de Reels não entram neste cálculo.</small></article>}</div></section>;
}
