import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { getWhatsAppManagerRuntime } from "@/lib/whatsapp-manager/runtime";
import { generateWhatsAppLink } from "@/lib/whatsapp/generate-link";
import { createEncurtaRequestId,createEncurtaShortLink,EncurtaError } from "@/lib/integrations/encurta";
import { checkRateLimit } from "@/lib/security/rate-limit";
import { errorResponse,readJsonBody,SafeHttpError,successResponse } from "@/lib/security/http";

export const runtime="nodejs";export const dynamic="force-dynamic";
const schema=z.strictObject({title:z.string().trim().min(1).max(120),phone:z.string().min(1).max(32),message:z.string().max(2000).optional(),labels:z.array(z.string().trim().min(1).max(30)).max(10).optional(),requestId:z.string().regex(/^[A-Za-z0-9][A-Za-z0-9_-]{7,99}$/).optional()});
export async function POST(request:Request){const requestId=createEncurtaRequestId();try{const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new SafeHttpError(401,"unauthorized","Entre na sua conta para criar um link.");const runtime=await getWhatsAppManagerRuntime();if(!runtime.enabled||!runtime.flags.whatsapp_manager_create_link)throw new SafeHttpError(503,"feature_disabled","A criação de links está temporariamente indisponível.");const rate=await checkRateLimit(request,"whatsapp-shortener",undefined,{limit:10,windowSeconds:86400,identity:`manager:${user.id}`});if(!rate.available)throw new SafeHttpError(503,"rate_limit_unavailable","A criação de links está temporariamente indisponível.");if(!rate.allowed)throw new SafeHttpError(429,"rate_limited","Você atingiu o limite diário de criação.");const{count}=await supabase.from("user_whatsapp_links").select("id",{count:"exact",head:true}).eq("user_id",user.id).is("deleted_at",null);if((count??0)>=10)throw new SafeHttpError(429,"plan_limit","Você atingiu o limite de links do plano atual.");const body=await readJsonBody(request,15000);const parsed=schema.safeParse(body);if(!parsed.success)throw new SafeHttpError(422,"validation_error","Revise os dados informados.");const official=generateWhatsAppLink({phone:parsed.data.phone,message:parsed.data.message??"",messageMaxCharacters:2000});const shortened=await createEncurtaShortLink({phone:official.phone.internationalNumber,message:parsed.data.message??"",requestId:parsed.data.requestId??requestId,officialUrl:official.url,accessLevel:"free",externalResourceId:`whatsapp_manager:${user.id}`});const{data,error}=await supabase.from("user_whatsapp_links").insert({user_id:user.id,encurta_link_id:shortened.id,title:parsed.data.title,phone:official.phone.internationalNumber,message:parsed.data.message??"",slug:shortened.slug,short_url:shortened.shortUrl,official_url:official.url,status:shortened.status,labels:parsed.data.labels??[],expires_at:shortened.expiresAt}).select("id,title,slug,short_url,status,created_at").single();if(error)throw new SafeHttpError(500,"persistence_failed","O link foi criado, mas não pôde ser associado à conta. Fale com o suporte e informe o código da solicitação.");await supabase.from("user_activity_logs").insert({user_id:user.id,action:"link_created",entity_id:data.id,metadata:{}});return successResponse({data},201,requestId)}catch(error){if(error instanceof SafeHttpError)return errorResponse(error,requestId);if(error instanceof EncurtaError){const status=error.code==="rate_limited"?429:error.code==="idempotency_conflict"?409:503;return errorResponse(new SafeHttpError(status,error.code,error.message),requestId)}return errorResponse(new SafeHttpError(500,"request_failed","Não foi possível criar o link."),requestId)}}
