import type { InstagramProfile } from "@/lib/social-providers/contracts/instagram-profile";
import type { ActionPlanItem, AdvancedAnalysisMetrics } from "./types";

const priorityWeight = { high: 3, medium: 2, low: 1 } as const;
export function buildActionPlan(profile: InstagramProfile, metrics: AdvancedAnalysisMetrics, maximum: number): ActionPlanItem[] {
  const candidates: ActionPlanItem[] = []; const push = (item: ActionPlanItem) => { if (!candidates.some((current) => current.category === item.category)) candidates.push(item); };
  const completeness = metrics.profileCompleteness;
  if (completeness?.available && completeness.score !== null && completeness.score < 65) push({ id: "complete-profile", priority: completeness.score < 40 ? "high" : "medium", category: "profile", title: "Complete os elementos básicos do perfil", description: "Alguns campos públicos importantes ainda não estão preenchidos.", evidence: `Completude de ${completeness.score}% e ${completeness.missingCriteria.length} critérios ausentes.`, suggestedAction: "Priorize os itens ausentes indicados na seção de completude.", confidence: completeness.confidence, sourceMetrics: ["profileCompleteness.score", "profileCompleteness.missingCriteria"] });
  if (!profile.externalUrl && /(compre|agende|orçamento|serviço|produto|fale|contato)/iu.test(profile.biography ?? "")) push({ id: "add-bio-destination", priority: "high", category: "bio", title: "Adicione um destino claro à bio", description: "A bio apresenta intenção comercial, mas não há link público disponível.", evidence: "Chamada comercial identificada na bio e link externo ausente.", suggestedAction: "Inclua um link confiável para contato, catálogo ou próxima etapa.", confidence: { level: "medium", sampleSize: 1, reason: "Regra baseada nos campos públicos da bio e do link." }, sourceMetrics: ["profile.externalUrl", "profile.biography"] });
  const cta = metrics.ctaAnalysis;
  if (cta?.available && cta.percentageWithCta !== null && cta.percentageWithCta < 20) push({ id: "use-cta", priority: "medium", category: "cta", title: "Torne o próximo passo mais explícito", description: "Poucos conteúdos orientam o público para uma ação concreta.", evidence: `${Math.round(cta.percentageWithCta)}% das ${cta.confidence.sampleSize} publicações analisadas apresentaram CTA.`, suggestedAction: "Teste chamadas específicas para comentários, salvamentos ou contato em parte dos próximos conteúdos.", confidence: cta.confidence, sourceMetrics: ["ctaAnalysis.percentageWithCta"] });
  const regularity = metrics.publishingRegularity;
  if (regularity?.available && ["irregular", "recently_inactive"].includes(regularity.classification)) push({ id: "editorial-regularity", priority: regularity.classification === "recently_inactive" ? "high" : "medium", category: "consistency", title: "Recupere uma cadência editorial previsível", description: "Os intervalos observados indicam baixa regularidade recente.", evidence: `${regularity.postsLast30Days} publicações em 30 dias; maior intervalo de ${Math.round(regularity.longestGapDays ?? 0)} dias.`, suggestedAction: "Use o próprio histórico como referência e adote uma frequência sustentável.", confidence: regularity.confidence, sourceMetrics: ["publishingRegularity.postsLast30Days", "publishingRegularity.longestGapDays"] });
  const performances = metrics.formatPerformance?.filter((item) => item.available && item.averageEngagementRate !== null).sort((a, b) => (b.averageEngagementRate ?? 0) - (a.averageEngagementRate ?? 0)); const best = performances?.[0], diversity = metrics.contentDiversity;
  if (best && diversity && best.format !== diversity.predominantFormat && diversity.counts[best.format] < Math.max(...Object.values(diversity.counts))) push({ id: "test-best-format", priority: "low", category: "formats", title: "Teste mais conteúdos no formato de melhor resposta", description: "O formato com melhor média não é o mais utilizado na amostra.", evidence: `${best.postsCount} conteúdos do formato ${best.format} sustentam a comparação disponível.`, suggestedAction: "Aumente o teste gradualmente e compare novamente antes de mudar toda a estratégia.", confidence: best.confidence, sourceMetrics: ["formatPerformance.averageEngagementRate", "contentDiversity.predominantFormat"] });
  return candidates.sort((a, b) => priorityWeight[b.priority] - priorityWeight[a.priority]).slice(0, Math.min(5, maximum));
}
