import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdminSession } from "@/lib/admin/auth";
import { getPocRun } from "@/lib/social-providers/scrape-creators/execution";
import { AdminPageHeader, AdminStatusBadge } from "@/components/admin/admin-ui";
import { deleteScrapeCreatorsRun } from "../../actions";
const json = (value: unknown) => JSON.stringify(value ?? null, null, 2);
export default async function RunPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireAdminSession("provider_poc.view"); const { id } = await params; const run = await getPocRun(id); if (!run) notFound(); const inventory = (run.field_inventory || {}) as Record<string, unknown>;
  return <><AdminPageHeader eyebrow="RESULTADO TÉCNICO" title={`Execução ${id.slice(0, 8)}`} description="Resposta de estudo da integração; não constitui diagnóstico ou relatório oficial." action={<div className="admin-form-actions"><Link className="admin-secondary-button" href={`/admin/api/scrapecreators/export/${id}?type=normalized`}>JSON normalizado</Link><Link className="admin-secondary-button" href={`/admin/api/scrapecreators/export/${id}?type=inventory`}>Inventário CSV</Link><Link className="admin-secondary-button" href={`/admin/api/scrapecreators/export/${id}?type=run`}>Relatório JSON</Link></div>} />
    <section className="admin-panel"><h2>Resumo</h2><dl className="admin-details"><dt>Status</dt><dd><AdminStatusBadge status={run.status} /></dd><dt>Endpoint</dt><dd>{run.endpoint}</dd><dt>Entrada</dt><dd className="admin-mono">{run.input_identifier}</dd><dt>Data</dt><dd>{new Date(run.created_at).toLocaleString("pt-BR")}</dd><dt>HTTP</dt><dd>{run.http_status ?? "—"}</dd><dt>Duração</dt><dd>{run.duration_ms} ms</dd><dt>Itens</dt><dd>{run.items_count}</dd><dt>Cache</dt><dd>{run.used_cache ? "Sim" : "Não"}</dd><dt>Chamadas</dt><dd>{run.calls_count}</dd><dt>Retries</dt><dd>{run.retries_count}</dd><dt>Créditos estimados</dt><dd>{run.estimated_credit_cost}</dd>{run.error_code && <><dt>Erro</dt><dd>{run.error_code}: {run.error_message}</dd></>}</dl></section>
    <div className="admin-grid-two"><section className="admin-panel"><h2>Campos disponíveis</h2><dl className="admin-details"><dt>Encontrados</dt><dd>{Array.isArray(inventory.found) ? inventory.found.length : 0}</dd><dt>Ausentes</dt><dd>{Array.isArray(inventory.missing) ? inventory.missing.join(", ") || "Nenhum" : "—"}</dd><dt>Nulos</dt><dd>{Array.isArray(inventory.null) ? inventory.null.join(", ") || "Nenhum" : "—"}</dd><dt>Desconhecidos</dt><dd>{Array.isArray(inventory.unknown) ? inventory.unknown.join(", ") || "Nenhum" : "—"}</dd></dl></section><section className="admin-panel"><h2>Validação</h2><pre className="admin-json-viewer">{json(run.validation_issues)}</pre></section></div>
    <section className="admin-panel"><h2>Dados normalizados</h2><pre className="admin-json-viewer">{json(run.normalized_result)}</pre></section><section className="admin-panel"><h2>Resposta bruta sanitizada</h2>{run.raw_response ? <pre className="admin-json-viewer">{json(run.raw_response)}</pre> : <p className="admin-muted">A resposta bruta não foi salva ou já expirou.</p>}</section>
    {session.profile.role === "super_admin" && <section className="admin-danger-zone"><h2>Excluir execução</h2><form action={deleteScrapeCreatorsRun} className="admin-confirm-grid"><input type="hidden" name="id" value={id} /><input name="confirmation" placeholder="Digite EXCLUIR" autoComplete="off" required /><button className="admin-danger-button">Excluir com auditoria</button></form></section>}</>;
}
