import Link from "next/link";
import { requireAdminSession } from "@/lib/admin/auth";
import { getPocSettings, listPocRuns } from "@/lib/social-providers/scrape-creators/execution";
import { AdminPageHeader, AdminStatCard, AdminStatusBadge } from "@/components/admin/admin-ui";
import { executeScrapeCreatorsTest } from "./actions";
export default async function ScrapeCreatorsPocPage({ searchParams }: { searchParams: Promise<{ erro?: string }> }) {
  await requireAdminSession("provider_poc.view"); const params = await searchParams; const runs = await listPocRuns(50); let settings = null;
  try { settings = await getPocSettings(); } catch { /* migration ainda não aplicada */ }
  const success = runs.filter((run) => run.status === "success").length, cached = runs.filter((run) => run.used_cache).length;
  const average = runs.length ? Math.round(runs.reduce((sum, run) => sum + Number(run.duration_ms || 0), 0) / runs.length) : 0;
  const totalCalls = runs.reduce((sum, run) => sum + Number(run.calls_count || 0), 0), totalCredits = runs.reduce((sum, run) => sum + Number(run.estimated_credit_cost || 0), 0);
  const inventories = runs.map((run) => (run.field_inventory || {}) as Record<string, unknown>); const found = inventories.reduce((sum, item) => sum + (Array.isArray(item.found) ? item.found.length : 0), 0), missing = inventories.reduce((sum, item) => sum + (Array.isArray(item.missing) ? item.missing.length : 0), 0);
  const endpoints = (["profile", "posts", "reels", "post_details"] as const).map((endpoint) => { const rows = runs.filter((run) => run.endpoint === endpoint); return { endpoint, count: rows.length, duration: rows.length ? Math.round(rows.reduce((sum, row) => sum + Number(row.duration_ms || 0), 0) / rows.length) : 0, items: rows.length ? (rows.reduce((sum, row) => sum + Number(row.items_count || 0), 0) / rows.length).toFixed(1) : "0", success: rows.length ? Math.round(rows.filter((row) => row.status === "success").length / rows.length * 100) : 0 }; });
  return <><AdminPageHeader eyebrow="INTEGRAÇÃO ADMINISTRATIVA" title="ScrapeCreators POC" description="Ferramenta técnica para validar respostas públicas do Instagram. Os dados não são relatório oficial da Alcance IA." />
    {params.erro && <p className="admin-error">{decodeURIComponent(params.erro)}</p>}
    <div className="admin-stat-grid"><AdminStatCard label="Execuções recentes" value={runs.length} /><AdminStatCard label="Taxa de sucesso" value={`${runs.length ? Math.round(success / runs.length * 100) : 0}%`} /><AdminStatCard label="Duração média" value={`${average} ms`} /><AdminStatCard label="Uso de cache" value={`${runs.length ? Math.round(cached / runs.length * 100) : 0}%`} /><AdminStatCard label="Chamadas" value={totalCalls} /><AdminStatCard label="Créditos estimados" value={totalCredits} /><AdminStatCard label="Itens médios" value={runs.length ? (runs.reduce((sum, run) => sum + Number(run.items_count || 0), 0) / runs.length).toFixed(1) : "0"} /><AdminStatCard label="Campos ausentes" value={`${found + missing ? Math.round(missing / (found + missing) * 100) : 0}%`} /></div>
    <div className="admin-grid-two"><section className="admin-panel"><h2>Executar teste</h2><p className="admin-note">Cada página pode consumir 1 crédito estimado. Ignorar cache pode gerar nova cobrança. Ferramenta exclusiva para administradores.</p>
      <form action={executeScrapeCreatorsTest} className="admin-form admin-poc-form"><label>Endpoint<select name="endpoint" defaultValue="profile"><option value="profile">Perfil</option><option value="posts">Publicações</option><option value="reels">Reels</option><option value="post_details">Detalhes de publicação ou Reel</option></select></label><label>Usuário, URL pública ou shortcode<input name="identifier" maxLength={200} placeholder="usuario ou https://www.instagram.com/p/..." required /></label><label>Máximo de páginas<input name="maxPages" type="number" min={1} max={settings?.maxPages ?? 3} defaultValue={1} required /></label><label className="admin-toggle-line"><input name="useCache" type="checkbox" defaultChecked />Usar cache</label><label className="admin-toggle-line"><input name="forceRefresh" type="checkbox" />Ignorar cache (pode consumir créditos)</label><label className="admin-toggle-line"><input name="saveRaw" type="checkbox" />Salvar resposta bruta sanitizada por {settings?.rawRetentionDays ?? 7} dias</label><div className="admin-poc-estimate"><strong>Estimativa:</strong> 1 chamada por página; padrão de uma página.</div><button className="admin-primary-button" type="submit">Executar teste</button></form></section>
      <section className="admin-panel"><h2>Estado dos controles</h2><dl className="admin-details"><dt>Ambiente</dt><dd>{process.env.SCRAPECREATORS_POC_ENABLED === "true" ? "Ativo" : "Inativo"}</dd><dt>Configuração</dt><dd>{settings?.enabled ? "Ativa" : "Inativa"}</dd><dt>Feature flag</dt><dd>{settings?.featureEnabled ? "Ativa" : "Inativa"}</dd><dt>Chave no servidor</dt><dd>{process.env.SCRAPECREATORS_API_KEY ? "Configurada" : "Ausente"}</dd><dt>Limite diário</dt><dd>{settings?.dailyLimit ?? "Indisponível"}</dd></dl><p className="admin-note">A chave nunca é exibida. Os três controles precisam estar ativos.</p></section></div>
    <section className="admin-panel admin-poc-runs"><h2>Métricas por endpoint</h2><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Endpoint</th><th>Testes</th><th>Sucesso</th><th>Duração média</th><th>Itens médios</th></tr></thead><tbody>{endpoints.map((row) => <tr key={row.endpoint}><td>{row.endpoint}</td><td>{row.count}</td><td>{row.success}%</td><td>{row.duration} ms</td><td>{row.items}</td></tr>)}</tbody></table></div></section>
    <section className="admin-panel admin-poc-runs"><div className="admin-panel-header"><h2>Execuções recentes</h2><Link href="/admin/integracoes/scrapecreators/execucoes">Ver todas</Link></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Data</th><th>Endpoint</th><th>Identificador</th><th>Status</th><th>Duração</th><th>Itens</th><th>Chamadas / créditos</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td><Link href={`/admin/integracoes/scrapecreators/execucoes/${run.id}`}>{new Date(run.created_at).toLocaleString("pt-BR")}</Link></td><td>{run.endpoint}</td><td className="admin-mono">{run.input_identifier}</td><td><AdminStatusBadge status={run.status} /> {run.used_cache ? "cache" : ""}</td><td>{run.duration_ms} ms</td><td>{run.items_count}</td><td>{run.calls_count} / {run.estimated_credit_cost}</td></tr>)}</tbody></table></div></section>
  </>;
}
