import { notFound } from "next/navigation";
import { requireAdminSession } from "@/lib/admin/auth";
import { hasPermission } from "@/lib/admin/permissions";
import { getAnalysisRequest } from "@/lib/admin/data";
import { updateAnalysisAction, criticalRecordAction } from "@/app/admin/actions/operations";
import { AdminActionForm } from "@/components/admin/admin-action-form";
import { AdminConfirmDialog } from "@/components/admin/admin-confirm-dialog";
import { AdminPageHeader, AdminStatusBadge } from "@/components/admin/admin-ui";
import { recalculateMetricsAction } from "./actions";

const dateTime = new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" });
export default async function AnalysisDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireAdminSession("analysis.view"); const { id } = await params; const data = await getAnalysisRequest(id); if (!data) notFound(); const row = data.record;
  return <><AdminPageHeader eyebrow="SOLICITAÇÃO" title={`@${row.instagram_username}`} description={`Criada em ${dateTime.format(new Date(row.created_at))}`} />
    <section className="admin-grid-two"><article className="admin-panel"><h2>Dados permitidos</h2><dl className="admin-details"><dt>ID</dt><dd className="admin-mono">{row.id}</dd><dt>URL normalizada</dt><dd>{row.instagram_profile_url}</dd><dt>Status</dt><dd><AdminStatusBadge status={row.status} /></dd><dt>Atualização</dt><dd>{dateTime.format(new Date(row.updated_at))}</dd><dt>Expiração</dt><dd>{dateTime.format(new Date(row.expires_at))}</dd><dt>Identificador anônimo</dt><dd className="admin-mono">{row.anonymous_session_id}</dd><dt>Usuário associado</dt><dd>{row.user_id || "Não"}</dd><dt>Anonimizada</dt><dd>{row.anonymized_at ? dateTime.format(new Date(row.anonymized_at)) : "Não"}</dd></dl></article>
      <article className="admin-panel"><h2>Atribuição</h2><dl className="admin-details"><dt>Origem</dt><dd>{row.utm_source || "direto"}</dd><dt>Mídia</dt><dd>{row.utm_medium || "—"}</dd><dt>Campanha</dt><dd>{row.utm_campaign || "—"}</dd><dt>Conteúdo</dt><dd>{row.utm_content || "—"}</dd><dt>Termo</dt><dd>{row.utm_term || "—"}</dd><dt>Referência</dt><dd>{row.referrer || "—"}</dd><dt>Página de entrada</dt><dd>{row.landing_page || "—"}</dd></dl></article></section>
    {hasPermission(session.profile.role, "analysis.manage") && <section className="admin-panel"><h2>Atendimento interno</h2><AdminActionForm action={updateAnalysisAction}><input type="hidden" name="id" value={row.id} /><div className="admin-form-row"><label>Status<select name="status" defaultValue={row.status}>{["pending","processing","preview_ready","completed","failed","cancelled","expired"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Observações internas<textarea name="notes" defaultValue={row.admin_notes || ""} maxLength={4000} /></label></div></AdminActionForm></section>}
    {hasPermission(session.profile.role, "analysis.manage") && <section className="admin-panel"><h2>Métricas determinísticas</h2><p className="admin-muted">Recalcula a partir do perfil e das publicações já persistidos. Esta ação não consulta a API nem consome créditos externos.</p><AdminActionForm action={recalculateMetricsAction} submitLabel="Recalcular métricas" pendingLabel="Recalculando…"><input type="hidden" name="id" value={row.id} /></AdminActionForm></section>}
    <section className="admin-panel"><h2>Histórico administrativo</h2>{data.history.length ? <table className="admin-table"><thead><tr><th>Data</th><th>Ação</th><th>Função</th></tr></thead><tbody>{data.history.map((item) => <tr key={item.id}><td>{dateTime.format(new Date(item.created_at))}</td><td>{item.action.replaceAll("_", " ")}</td><td>{item.admin_role}</td></tr>)}</tbody></table> : <p className="admin-muted">Nenhuma alteração administrativa registrada.</p>}</section>
    {hasPermission(session.profile.role, "analysis.delete") && <section className="admin-danger-zone"><h2>Privacidade e exclusão</h2><p>A anonimização mantém apenas dados operacionais não identificáveis. A exclusão remove o registro.</p><div className="admin-form-actions"><AdminConfirmDialog action={criticalRecordAction} id={row.id} operation="anonymize_analysis" expected="ANONIMIZAR" title="Anonimizar solicitação" description="Nome de perfil, URLs, sessão, UTMs e identificadores pessoais serão removidos." buttonLabel="Anonimizar" danger={false} /><AdminConfirmDialog action={criticalRecordAction} id={row.id} operation="delete_analysis" expected="EXCLUIR" title="Excluir solicitação" description="O registro será removido permanentemente, mantendo somente a auditoria da ação." buttonLabel="Excluir" /></div></section>}
  </>;
}
