import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import { siteConfig } from "@/config/site";
import { generatePageMetadata } from "@/lib/seo/generate-page-metadata";
import { getPageContent, splitItems } from "@/lib/content/page-content";
import styles from "./page.module.css";

const benefits=[["↗","Links curtos","Transforme links longos do WhatsApp em endereços simples e fáceis de compartilhar."],["▦","QR Codes","Gere QR Codes para materiais impressos, vitrines, cartões digitais e páginas de contato."],["⌁","Métricas de acesso","Acompanhe cliques, períodos de maior atividade e o desempenho de cada link."],["◉","Controle de status","Ative, desative, edite ou defina uma data de expiração quando a API oferecer suporte."],["⌕","Organização","Use títulos, etiquetas e filtros para encontrar rapidamente cada link."],["✦","Mensagens personalizadas","Configure mensagens diferentes para atendimento, orçamento, suporte ou campanhas."]] as const;
const steps=[["01","Crie sua conta","Cadastre-se com e-mail ou use sua Conta Google quando disponível."],["02","Informe o WhatsApp","Digite o número brasileiro e escreva uma mensagem opcional."],["03","Gere o link","O Encurta.io cria um endereço curto exclusivo."],["04","Compartilhe e acompanhe","Use o link ou QR Code e acompanhe os cliques pelo painel."]] as const;
const uses=["Atendimento comercial","Solicitação de orçamento","Suporte","Bio do Instagram","Catálogo digital","Campanhas","Cartão de visita","Embalagem","Loja física","Eventos","E-mail","Landing pages"];
const faqs=[["O que é o Gerenciador de Links WhatsApp?","É uma área autenticada para criar, organizar e acompanhar links curtos que abrem conversas no WhatsApp."],["Preciso ter uma conta?","Sim. Os links e métricas são vinculados a uma conta para preservar controle e isolamento."],["Posso criar mais de um link?","Sim, respeitando o limite configurado para o nível de acesso da conta."],["O link utiliza o domínio Encurta.io?","Sim. A URL curta é criada pelo Encurta.io por uma integração privada entre servidores."],["Posso editar o telefone ou a mensagem?","Somente quando o contrato da API do Encurta.io suportar essa operação. A interface não simula mudanças apenas locais."],["O link continuará com o mesmo endereço após a edição?","Isso dependerá da capacidade de atualização disponibilizada pelo Encurta.io."],["É possível gerar QR Code?","Sim. O QR Code aponta para a URL curta e é gerado localmente, sem serviço externo de QR Code."],["Como os cliques são contabilizados?","O Encurta.io registra acessos ao redirecionamento e a Alcance IA exibe apenas agregados disponibilizados pela integração."],["Bots podem aparecer nas métricas?","Podem. Quando o provedor oferecer classificação, humanos e bots serão identificados como estimativas."],["O sistema envia mensagens automaticamente?","Não. Ele apenas abre uma conversa com uma mensagem opcional preenchida para você revisar e enviar."],["A Alcance IA acessa minhas conversas?","Não. O gerenciador não solicita sua senha do WhatsApp nem possui acesso às conversas."],["Posso desativar ou excluir um link?","Essas ações serão liberadas apenas quando os contratos correspondentes do Encurta.io estiverem homologados. Arquivar não desativa o link."],["Os links expiram?","A expiração é opcional quando suportada pelas capacidades disponibilizadas pelo Encurta.io."],["A ferramenta é gratuita?","Há uma configuração inicial gratuita com limites administrativos. Não há cobrança nesta fase."],["Posso usar o link em campanhas e redes sociais?","Sim, desde que o conteúdo e a distribuição respeitem as regras das plataformas e a legislação aplicável."]] as const;

export async function generateMetadata():Promise<Metadata>{return generatePageMetadata("whatsapp_link_manager",{robots:{index:true,follow:true}})}

export default async function ManagerLanding(){
  const content=await getPageContent("whatsapp_link_manager");
  const structured=[{"@context":"https://schema.org","@type":"WebApplication",name:"Gerenciador de Links WhatsApp",applicationCategory:"BusinessApplication",operatingSystem:"Web",url:`${siteConfig.url}/recursos/gerenciador-links-whatsapp`,description:"Crie links curtos do WhatsApp, gere QR Codes e acompanhe métricas agregadas.",offers:{"@type":"Offer",price:"0",priceCurrency:"BRL"}},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Início",item:siteConfig.url},{"@type":"ListItem",position:2,name:"Recursos",item:`${siteConfig.url}/recursos`},{"@type":"ListItem",position:3,name:"Gerenciador de Links WhatsApp",item:`${siteConfig.url}/recursos/gerenciador-links-whatsapp`}]},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}];
  return <main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,"\u003c")}}/>
    <section className={styles.hero}><div className={`${styles.container} ${styles.heroGrid}`}><div><nav className={styles.breadcrumb}><Link href="/">Início</Link><span>/</span><Link href="/recursos">Recursos</Link><span>/</span><strong>Gerenciador</strong></nav><span className={styles.eyebrow}>{content.eyebrow}</span><h1>{content.title}</h1><p className={styles.lead}>{content.description}</p><ul className={styles.checks}>{splitItems(content.checks).map((item)=><li key={item}>{item}</li>)}</ul><div className={styles.actions}><Link href="/criar-conta">{content.primary_button}</Link><Link href="/entrar">{content.secondary_button}</Link></div><p className={styles.notice}>◇ {content.notice}</p></div><DashboardMock/></div></section>
    <section className={styles.demo}><div className={styles.container}><Header eyebrow="DO CONTATO AO RESULTADO" title="Um fluxo simples, do número às métricas"/><div className={styles.demoFlow}><Demo label="NÚMERO E MENSAGEM" value="(71) 99999-9999" note="Número ilustrativo"/><i>→</i><Demo label="LINK CURTO" value="encurta.io/Ab7xP2" note="Ativo · demonstração"/><i>→</i><Demo label="QR CODE" value="▦" note="Pronto para baixar"/><i>→</i><Demo label="CLIQUES" value="248" note="Dado demonstrativo"/></div></div></section>
    <Section title={content.features_title} eyebrow="RECURSOS"><div className={styles.cardGrid}>{benefits.map(([icon,title,text])=><article key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></Section>
    <section className={styles.dark}><div className={styles.container}><Header eyebrow="COMO FUNCIONA" title={content.steps_title}/><div className={styles.steps}>{steps.map(([number,title,text])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <Section title={content.uses_title} eyebrow="CASOS DE USO"><div className={styles.useGrid}>{uses.map((use,index)=><article key={use}><span>{["↗","$","?","◎","▤","◈"][index%6]}</span><div><h3>{use}</h3><p>Crie um caminho direto e identificável para este canal.</p></div></article>)}</div></Section>
    <section className={styles.metrics}><div className={`${styles.container} ${styles.metricsGrid}`}><div><span className={styles.eyebrow}>MÉTRICAS AGREGADAS</span><h2>{content.metrics_title}</h2><p>{content.metrics_text}</p><p className={styles.notice}>Os dados vêm dos agregados do Encurta.io. Estimativas são identificadas e eventos individuais não são necessários.</p></div><div className={styles.chartMock}><header><span>Desempenho</span><small>Demonstração</small></header><strong>1.284 <small>cliques</small></strong><div className={styles.bars}>{[35,52,44,72,61,84,70,91,78,96,88,100].map((height,index)=><i key={index} style={{height:`${height}%`}}/>)}</div><footer><span>Dispositivos</span><b>Mobile 78%</b></footer></div></div></section>
    <Section title={content.security_title} eyebrow="SEGURANÇA"><div className={styles.security}><div>◇</div><ul><li>Links vinculados à conta e protegidos por RLS</li><li>Destinos validados antes da criação</li><li>Desativação e expiração quando suportadas</li><li>Nenhum envio automático ou leitura de conversas</li><li>Comunicação privada entre Alcance IA e Encurta.io</li></ul></div></Section>
    <section className={styles.faq}><div className={styles.container}><Header eyebrow="DÚVIDAS FREQUENTES" title={content.faq_title}/>{faqs.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className={styles.final}><div className={styles.container}><span>COMECE GRÁTIS</span><h2>{content.final_title}</h2><p>{content.final_text}</p><div className={styles.actions}><Link href="/criar-conta">{content.primary_button}</Link><Link href="/entrar">{content.secondary_button}</Link></div></div></section>
  </main>
}
function Header({eyebrow,title}:{eyebrow:string;title:string}){return <header className={styles.heading}><span>{eyebrow}</span><h2>{title}</h2></header>}
function Section({title,eyebrow,children}:{title:string;eyebrow:string;children:ReactNode}){return <section className={styles.section}><div className={styles.container}><Header eyebrow={eyebrow} title={title}/>{children}</div></section>}
function Demo({label,value,note}:{label:string;value:string;note:string}){return <div><small>{label}</small><strong>{value}</strong><span>{note}</span></div>}
function DashboardMock(){return <div className={styles.mock}><header><span><i/> Painel de links</span><small>Demonstração</small></header><div className={styles.mockStats}><article><small>Cliques totais</small><strong>1.284</strong><span>↑ 12,4% ilustrativo</span></article><article><small>Links ativos</small><strong>08</strong><span>de 10 links</span></article></div><article className={styles.mockLink}><header><div><strong>Atendimento comercial</strong><small>Criado em 18 jul. 2026</small></div><b>Ativo</b></header><a>encurta.io/Ab7xP2</a><div><span className={styles.fakeQr}>▦</span><div className={styles.spark}>{[30,48,36,70,52,83,65,92].map((height,index)=><i key={index} style={{height:`${height}%`}}/>)}</div></div><footer><span>248 cliques · demonstração</span><button>Copiar</button></footer></article></div>}
