import Link from "next/link";
import { requireAdminSession } from "@/lib/admin/auth";
import { hasPermission } from "@/lib/admin/permissions";
import { AdminPageHeader, AdminStatusBadge } from "@/components/admin/admin-ui";
import { AdminActionForm } from "@/components/admin/admin-action-form";
import { getOpenAIAdminOverview } from "@/lib/ai/admin-data";
import { getConfiguredModelName, isOpenAIEnvironmentEnabled } from "@/lib/ai/providers/openai/config";
import { getAIRuntimeConfig } from "@/lib/ai/runtime-config";
import { PROFILE_ANALYSIS_PROMPT_VERSION } from "@/lib/ai/prompts/prompt-version";
import { AI_ANALYSIS_SCHEMA_VERSION } from "@/lib/ai/schemas/profile-analysis-schema";
import { generateAdminAIAnalysisAction } from "./actions";

export default async function OpenAIIntegrationPage() {
  const session = await requireAdminSession("ai_integration.view"); const [overview, runtime] = await Promise.all([getOpenAIAdminOverview(), getAIRuntimeConfig()]); const model = getConfiguredModelName(); const canExecute = hasPermission(session.profile.role, "ai_integration.execute");
  return <><AdminPageHeader eyebrow="INTEGRAÇÃO" title="OpenAI" description="Interpretação assistiva, estruturada e isolada das métricas determinísticas." action={<Link className="admin-button admin-button-secondary" href="/admin/integracoes/openai/execucoes">Ver execuções</Link>} />
    <section className="admin-grid-two"><article className="admin-panel"><h2>Estado dos controles</h2><dl className="admin-details"><dt>Ambiente</dt><dd>{isOpenAIEnvironmentEnabled() ? "Ativo" : "Inativo"}</dd><dt>Configuração</dt><dd>{runtime.config.enabled ? "Ativa" : "Inativa"}</dd><dt>Feature flag mestre</dt><dd>{runtime.flags.profileAnalysis ? "Ativa" : "Inativa"}</dd><dt>Chave no servidor</dt><dd>{process.env.OPENAI_API_KEY ? "Configurada" : "Ausente"}</dd><dt>Modelo</dt><dd>{model || "Não configurado"}</dd><dt>Prompt</dt><dd className="admin-mono">{PROFILE_ANALYSIS_PROMPT_VERSION}</dd><dt>Schema</dt><dd className="admin-mono">{AI_ANALYSIS_SCHEMA_VERSION}</dd><dt>Engajamento liberado</dt><dd>{runtime.config.engagementInterpretationAudited ? "Sim" : "Não — bloqueado até auditoria formal"}</dd></dl><p className="admin-note">A chave nunca é exibida nem armazenada no Supabase.</p></article>
      <article className="admin-panel"><h2>Uso de hoje</h2><dl className="admin-details"><dt>Execuções</dt><dd>{overview.totals.executions}</dd><dt>Taxa de sucesso</dt><dd>{overview.totals.successRate.toFixed(1)}%</dd><dt>Tokens</dt><dd>{overview.totals.tokens.toLocaleString("pt-BR")}</dd><dt>Custo estimado</dt><dd>{overview.totals.estimatedCostUsd ? `US$ ${overview.totals.estimatedCostUsd.toFixed(4)}` : "Não configurado"}</dd><dt>Tempo médio</dt><dd>{Math.round(overview.totals.averageDurationMs)} ms</dd><dt>Cache hits</dt><dd>{overview.totals.cacheHits}</dd></dl></article></section>
    {canExecute && <section className="admin-panel"><h2>Teste controlado</h2><p className="admin-muted">Executa somente versões definidas no código. Não aceita prompt arbitrário. A operação consome tokens quando não reutiliza o cache.</p><AdminActionForm action={generateAdminAIAnalysisAction} submitLabel="Gerar interpretação" pendingLabel="Gerando…"><label>Análise<select name="requestId" required defaultValue=""><option value="" disabled>Selecione</option>{overview.analyses.map((item) => <option key={item.id} value={item.id}>@{item.instagram_username} · {item.id.slice(0, 8)}</option>)}</select></label><fieldset><legend>Recursos</legend><label><input type="checkbox" name="summary" defaultChecked /> Resumo</label><label><input type="checkbox" name="bioAnalysis" defaultChecked /> Bio</label><label><input type="checkbox" name="recommendations" defaultChecked /> Recomendações</label><label><input type="checkbox" name="contentIdeas" defaultChecked /> Ideias</label><label><input type="checkbox" name="actionPlanExplanation" defaultChecked /> Explicação do plano</label></fieldset><label><input type="checkbox" name="bypassCache" /> Forçar atualização (consome uma nova chamada)</label><p className="admin-note">Modelo: {model || "ausente"} · prompt: {PROFILE_ANALYSIS_PROMPT_VERSION} · máximo de saída: {process.env.OPENAI_MAX_OUTPUT_TOKENS || "1800"} tokens.</p></AdminActionForm></section>}
    <section className="admin-panel"><h2>Erros recentes</h2>{overview.rows.filter((row) => row.error_code).length ? <table className="admin-table"><thead><tr><th>Status</th><th>Código</th><th>Modelo</th><th>Data</th></tr></thead><tbody>{overview.rows.filter((row) => row.error_code).slice(0, 10).map((row) => <tr key={row.id}><td><AdminStatusBadge status={row.status} /></td><td>{row.error_code}</td><td>{row.model}</td><td>{new Date(row.created_at).toLocaleString("pt-BR")}</td></tr>)}</tbody></table> : <p className="admin-muted">Nenhum erro registrado hoje.</p>}</section>
  </>;
}
